// Map tileId to its specific illustration image
export const TILE_IMAGE: Record<number, string> = {
  0:  '/images/go.webp',
  1:  '/images/camau.webp',
  2:  '/images/bentre.webp',
  3:  '/images/cantho.webp',
  4:  '/images/port.webp',
  5:  '/images/longan.webp',
  6:  '/images/vinhlong.webp',
  7:  '/images/mytho.webp',
  8:  '/images/jail.webp',
  9:  '/images/danang.webp',
  10: '/images/hoian.webp',
  11: '/images/hue.webp',
  12: '/images/chance.webp',
  13: '/images/dienbien.webp',
  14: '/images/port.webp',
  15: '/images/mocchau.webp',
  16: '/images/festival.webp',
  17: '/images/nhatrang.webp',
  18: '/images/port.webp',
  19: '/images/phuquoc.webp',
  20: '/images/chance.webp',
  21: '/images/ninhbinh.webp',
  22: '/images/halong.webp',
  23: '/images/hanoi.webp',
  24: '/images/airport.webp',
  25: '/images/port.webp',
  26: '/images/vungtau.webp',
  27: '/images/hcm.webp',
  28: '/images/chance.webp',
  29: '/images/thanhhoa.webp',
  30: '/images/tax.webp',
  31: '/images/dalat.webp',
};
